trigger: none
pr: none

variables:
  PACKER_VERSION: '1.12.0'

# Tenant variables:
  AGENT_POOL: "LZ-cn-xxxx-dev"
  SERVICE_CONNECTION: "lz-cn-spn-image"
  AZURE_CLOUD_ENV: "AzureChinaCloud"
  TENANT_ID: "12345678"
  SUBSCRIPTION_ID: "1234567890"
  LOCATION: "chinanorth3"


# Os variables:
  OS_NAME_FORMATTED: "Ubuntu_2204_ADOagent_gen1"
  MANAGED_IMAGE_NAME: "ubuntu2204"
  IMAGE_SKU: "22_04-lts"
  IMAGE_OFFER: "0001-com-ubuntu-server-jammy"
  IMAGE_PUBLISHER: "Canonical"
  OS_TYPE: "Linux"
  VM_SIZE: "Standard_DS2_v2"

# image Gallery variables:
  SIG_RG: "rg-shared-image-gallery-chinanorth3"
  SIG_NAME: "shared_image_gallery_cn3"

stages:
  - template: "./templates/packer-build-ado-image.yml"
    parameters:
      tenantID: "$(AZURE_TENANT_ID)"
      subscriptionID: "$(SUBSCRIPTION_ID)"
      serviceConnection: "$(SERVICE_CONNECTION)"
      imageGalleryRG: "$(SIG_RG)"
      imageGalleryName: "$(SIG_NAME)"
      imageGalleryDifName: "$(OS_NAME_FORMATTED)"