trigger: none
pr: none

variables:
  TF_VERSION: '1.11.2'
  IS_MAIN: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}

  AGENT_POOL: "LZ-cn-dev"
  SERVICE_CONNECTION: "lz-cn-spn-image"

  RM_RG_NAME: 'rg-backend-chinanorth3'
  RM_SA_NAME: "satfstate"
  RM_CONTAINER_NAME: 'state'
  RM_Key: "image-backend.tfstate"

stages:
  - template: "templates/sig-infra.yml"
    parameters:
      pipelineName: "Share_Image_Builder"
      backendServiceArm: $(SERVICE_CONNECTION)
      backendAzureRmResourceGroupName: $(RM_RG_NAME)
      backendAzureRmStorageAccountName: $(RM_SA_NAME)
      backendAzureRmContainerName: $(RM_CONTAINER_NAME)
      backendAzureRmKey: $(RM_Key)